### ISSUE TITLE
Getting this running w/RM57Lx LaunchPad

### ISSUE THREAD

**Issue by kenkeiter** [paoloteti/ti-hercules-bsp#2]
Hi @paoloteti –

Awesome work on this, thus far!! 

I'm using TI's RM57Lx Launchpad board, and I believe I'm getting hung up on a panic within `phantom_interrupt()` – although it's hard to tell, because I haven't been able to get OpenOCD up and running for this board, yet. Any tips, and can you elaborate on your own development setup?

Best,
K

**Comment by paoloteti** [comment]
RM57Lx is a Little-endian device, but this project support, at the moment, only TMS570x devices that are Big-endian devices
This project use `armebv7r-none-eabihf` and `armeb-none-eabi` as linker,  where `eb` = big-endian.

You can create your own device spec. (armv7r-none-eabihf) as json file, test it and then, if you want to have it upstream, push a PR similar to 50813 on `rust-lang/rust`.

We have a plan to add armv7r-none-eabihf on rust-lang/rust, so any help is appreciated.

**Comment by kenkeiter** [comment]
That's a great hint. Thank you! I need to be a bit more rigorous and actually take the time to read the chip's doc and errata – otherwise I would have caught the issue with the endianness. I'll look into submitting an upstream device spec. Definitely appreciate your efforts here.

**Comment by paoloteti** [comment]
We sent out some PR to enable support from Cortex-R LE.  (see [#53663](https://github.com/rust-lang/rust/pull/53663)) and so to enable support for TI RMx MCUs

**Comment by kenkeiter** [comment]
@paoloteti I saw that! I was talking to @japaric about it yesterday in #rust-embedded – but I was anticipating needing to make that PR myself. Thanks to both of you!!

**Comment by paoloteti** [comment]
Ok perfect. Sorry guys I was not aware of this and I'm not on #rust-embedded for two reason: company firewall and local timezone.

**Comment by paoloteti** [comment]
Not yet merged on `master`, but on `next` branch you can find what you need to run this BSP on pre-built Cortex-R targets. So here it is:

![image](https://user-images.githubusercontent.com/35451649/44805723-4b000680-abc5-11e8-91cd-301a7d3567d1.png)

**Comment by kenkeiter** [comment]
@paoloteti You rock! This is awesome 🎊
